### ISSUE TITLE
test mts with base and zcu208

### ISSUE THREAD

**Issue by julianctrt** [Xilinx/RFSoC-PYNQ#13]
Hello again,

in vivado base project for zcu208 evaluation board I discover the user_sysref_adc and user_sysref_dac are not connected so it's not possible to evaluate the multi-tile-sync with this project besides the ip core is configured to do it,

 and since also I can't modify this project since I can't compile it and test it like expressed in other issue

https://github.com/Xilinx/RFSoC-PYNQ/issues/12

**Comment by nathanjachimiec** [comment]
Note that the design is not meant to demonstrate MTS.  MTS is planned for a future release.  Modifications are necessary not just to the overlay, but also the xrfdc driver and providing CLK104 synthesizer settings.

**Comment by mariodruiz** [comment]
@julianctrt,

MTS design is now available for the ZCU208 here https://github.com/Xilinx/RFSoC-MTS
