### ISSUE TITLE
Any plan to support ZCU216 board ? 

### ISSUE THREAD

**Issue by WeiCheng14159** [Xilinx/RFSoC-PYNQ#26]
Hi, 
I came across this repo and found that there is currently no support for the ZCU216 board. 
Do you plan to support ZCU216 board in the near future?

**Comment by mariodruiz** [comment]
Hi @WeiCheng14159,

There are steps to build an SD card with the PYNQ image provided by the community: https://discuss.pynq.io/t/pynq-for-zcu216-rfsoc-board/3056/6

**Comment by WeiCheng14159** [comment]
Their PYNQ image is built with PYNQ 2.7 and VIvado 2020.2. I have tried to fast forward that repo to PYNQ 3.0 and Vivado 2022.1; however, that doesn't succeed (stuck in boot loop).
My question is, to your best knowledge, is ZCU216 board fully supported by PYNQ 3.0 yet?
