### ISSUE TITLE
Regarding RFSoC board for academic usage 

### ISSUE THREAD

**Issue by WeiCheng14159** [Xilinx/RFSoC-PYNQ#28]
Hi,

Thank you for creating a Python interface for the RFSoC platform. It is very beneficial for researchers who are not familiar with lower-level logic to conduct RF experiments. We have been looking into this and are wondering how to obtain an RFSoC board from Xilinx for academic use. We have submitted purchase requests (through xup@amd.com) to the XUP (Xilinx University Program) following the guidelines indicated on Xilinx's official purchasing page; however, we haven't received any response yet. Do you know of any other ways to contact them besides sending an email to xup@amd.com?

**Comment by andrewgschmidt** [comment]
Hi, we have received your request and will respond through that email.  Thanks for reaching out!
