### ISSUE TITLE
Base Overlay ZCU111

### ISSUE THREAD

**Issue by jlanzuela** [Xilinx/RFSoC-PYNQ#9]
Hi there!

First of all, I wanna congratulate and thank you for your great work. 

I am developing with the ZCU111 and I have one question. For the boards RFSoC2x2, RFSoC4x2 and ZCU208 I have found the base overlay on which I can do some modifications like insert my own blocks IP into the PL for stimulate the DAC but not in the ZCU111.

Have any base overlay compatible with ZCU111? RFSoC2x2 base overlay maybe?

Many thanks again, best regards,
Jorge

**Comment by schelleg** [comment]
hi @jlanzuela - we do not have a base overlay for the ZCU111, but there is an RFSoC spectrum analyzer here that we recommend people try out.
https://github.com/strath-sdr/rfsoc_sam
